language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - pip install -r test_requirements.txt
  - pip install .
script: py.test --cov=tmb --pep8=tmb -v --cov=tmb --cov-report term-missing tests/
after_success: coveralls