language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - pip install -r test_requirements.txt
  - pip install .
script: py.test -v --cov=tmb --cov-report term-missing tests/
after_script: coveralls